# Generated by Django 4.2.7 on 2025-07-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0003_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='preview_image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
